Integrate web branding
bento-platform/bentoV2 pull request #81
Opened 2022-12-15 17:44 UTC by brouillette

- added capacity to change branding logo

2022-12-15 17:48 UTC, davidlougheed commented
the default PNG is already in the image itself, does it make sense to remount it here?

2022-12-15 17:50 UTC, brouillette commented
> the default PNG is already in the image itself, does it make sense to remount it here?

I couldn't find a way to conditionally mount the volume (i.e. only mount this new png if there is one), so simply mounting the default, and overriding if necessary, was the first go-to

2022-12-16 02:59 UTC, davidlougheed approved these changes

2022-12-16 17:53 UTC, davidlougheed requested changes
I re-cropped the bento logo for branding purposes (in the runtime config branch) so can you replace the default branding logo with that one here?

2022-12-16 19:12 UTC, davidlougheed approved these changes

2022-12-16 19:13 UTC, merged